# Shared constants and helpers for github_runner scripts.
# This file is sourced by every script under script/ (init, add-runner,
# remove-runner, status, update, uninstall, cleanup, schedule-cleanup)
# -- variables that look unused here are consumed in those scripts.
# shellcheck shell=bash
# shellcheck disable=SC2034

# RUNNER_HOME holds the tarball cache (.bin/) and per-target runner install
# dirs (<org>/_org/, <owner>/<repo>/). It defaults to <repo_root>/runners/
# (i.e. alongside this checkout) so a single clone owns all runner state
# without polluting $HOME. Override with RUNNER_HOME=... before invoking
# any script to install runners elsewhere.
if [[ -z "${RUNNER_HOME:-}" ]]; then
  RUNNER_HOME="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)/runners"
fi
# SEC-3: RUNNER_HOME becomes the rm -rf root for remove-runner / uninstall /
# cleanup, so refuse dangerous overrides lexically here -- the single
# chokepoint. Validated without requiring the dir to exist, so a first
# install (dir not yet created) is not broken. --preserve-root would not
# help: every consumer derives a SUBPATH (/.bin, /<org>/_org).
[[ "${RUNNER_HOME}" = /* ]] || { echo "FATAL: RUNNER_HOME must be absolute: '${RUNNER_HOME}'" >&2; exit 1; }
RUNNER_HOME="${RUNNER_HOME%/}"
case "${RUNNER_HOME}" in
  ""|/|/.|/..|"${HOME:-}") echo "FATAL: refusing RUNNER_HOME='${RUNNER_HOME}'" >&2; exit 1 ;;
esac
case "/${RUNNER_HOME}/" in
  */../*) echo "FATAL: RUNNER_HOME must be normalized (no '..'): '${RUNNER_HOME}'" >&2; exit 1 ;;
esac
readonly RUNNER_HOME

# Path to the optional registration config (KEY=value, shell-sourceable).
# Generated by script/configure.sh; consumed by load_config below. Lives
# under RUNNER_HOME (gitignored runner state), so config ports with the
# runner state, not the repo.
readonly SETUP_CONF="${RUNNER_HOME}/setup.conf"

# Runner Layout: the single source of truth for where runners live on disk
# and how they are named (dir, agent name, _org sentinel, .runner marker,
# systemd unit, active version). Sourced after RUNNER_HOME so its consumers
# (resolve_target, list_runners, runner_service_running, cleanup.sh) can read
# it at call time.
# shellcheck source=lib/runner-layout.sh
source "$(dirname "${BASH_SOURCE[0]}")/runner-layout.sh"

# Runner Service: the seam over a runner's systemd service (svc.sh lifecycle +
# the running? check). Sourced after runner-layout.sh, whose
# runner_service_unit_pattern it uses.
# shellcheck source=lib/runner-service.sh
source "$(dirname "${BASH_SOURCE[0]}")/runner-service.sh"

# Runner Release: the actions/runner release tarball (version, name, cache
# path, download URL, integrity verify). Sourced after RUNNER_HOME; reaches
# GitHub through the _gh seam at call time.
# shellcheck source=lib/runner-release.sh
source "$(dirname "${BASH_SOURCE[0]}")/runner-release.sh"

# Runner Config: the seam over a runner's bundled config.sh (register /
# deregister), sibling of runner-service.sh.
# shellcheck source=lib/runner-config.sh
source "$(dirname "${BASH_SOURCE[0]}")/runner-config.sh"

# Runner Container: the per-job container provisioner (ADR-0001 Phase 3, #82) --
# wraps the ephemeral run in a fresh, single-use, rootless container (podman else
# docker, --rm) so no state survives the job. It is the SINGLE place the
# `run.sh --jitconfig <encoded>` invocation lives (the JIT config is minted by
# the Go scale-set client, ADR-0001/ADR-0003).
# shellcheck source=lib/runner-container.sh
source "$(dirname "${BASH_SOURCE[0]}")/runner-container.sh"

# Validate a labels CSV: one or more comma-separated tokens, each matching
# GitHub's allowed label charset [A-Za-z0-9_-]+. Rejects empty input,
# whitespace, and leading / trailing / doubled commas. Returns 0 (valid)
# or 1 (invalid); prints nothing.
validate_labels() {
  [[ "${1:-}" =~ ^[A-Za-z0-9_-]+(,[A-Za-z0-9_-]+)*$ ]]
}

# SEC-4: GitHub owner/org and repo name validators. Owner/org is alphanumerics
# with single internal hyphens (GitHub's rule); repo additionally allows '.'
# and '_' but is never '.' or '..'. Both reject slashes and path traversal, so
# values that reach TARGET_DIR (an rm -rf root) and gh API paths stay safe.
valid_owner() { [[ "$1" =~ ^[A-Za-z0-9](-?[A-Za-z0-9])*$ ]]; }
valid_repo()  { [[ "$1" =~ ^[A-Za-z0-9._-]+$ && "$1" != . && "$1" != .. ]]; }

# H3: anchor an rm target under RUNNER_HOME lexically. A dir is acceptable
# iff "<dir>/" is prefixed by "${RUNNER_HOME}/", so no future change can turn
# a destructive rm into an out-of-tree delete. Defense-in-depth on top of the
# SEC-3 RUNNER_HOME normalization + resolve_target's identifier validation.
# Returns 0 (under RUNNER_HOME) or prints a refusal to stderr and returns 1.
assert_under_runner_home() {
  local dir=$1
  case "${dir}/" in
    "${RUNNER_HOME}/"*) return 0 ;;
    *) echo "refusing rm outside RUNNER_HOME: ${dir}" >&2; return 1 ;;
  esac
}

# Resolve registration labels from the optional setup.conf, leaving $LABELS
# holding the result (default "gpu" when unset / no config file). Called by
# init.sh / add-runner.sh before invoking the runner's config.sh, so a fresh
# install with no setup.conf keeps the historical gpu-only behavior.
#
# SEC-6: setup.conf lives under RUNNER_HOME and is writable by the runner
# user, so a CI job could drop arbitrary shell into it. We therefore EXTRACT
# the LABELS value with sed instead of sourcing the file (which would execute
# any other lines), then re-validate it -- failing closed on anything that
# isn't a clean labels CSV. sed '.../p | tail -1' is busybox-portable and
# mirrors configure.sh's "last LABELS= line wins" upsert.
load_config() {
  LABELS=""
  if [[ -f "${SETUP_CONF}" ]]; then
    LABELS=$(sed -n 's/^LABELS=//p' "${SETUP_CONF}" | tail -1)
  fi
  if [[ -n "${LABELS}" ]] && ! validate_labels "${LABELS}"; then
    echo "FAIL: invalid LABELS in ${SETUP_CONF}: '${LABELS}'" >&2
    exit 1
  fi
  LABELS="${LABELS:-gpu}"
}

# (RUNNER_VERSION_FALLBACK + resolve_runner_version moved to
# lib/runner-release.sh, with the rest of the release-tarball concern.)

# (find_cached_tarball moved to lib/runner-release.sh.)

# Enumerate every configured runner under RUNNER_HOME. Emits one
# TAB-separated row per runner. Org-scoped rows have 4 fields; repo-scoped
# rows append a 5th:
#
#   org-scoped:   scope \t org   \t name \t runner_dir
#   repo-scoped:  scope \t owner \t name \t runner_dir \t repo
#
# The variable-arity shape exists so callers can `IFS=$'\t' read -r scope
# org name runner_dir scope_id`; bash collapses adjacent tabs when IFS is
# whitespace, so a fixed-arity row with an empty middle field would lose
# alignment. Trailing-optional avoids that.
#
# Fields:
#   scope      -- "org" or "repo"
#   org        -- org name (for org scope) or owner name (for repo scope)
#   name       -- agentName read from the .runner JSON marker file
#   runner_dir -- absolute path to the actions/runner state dir
#   scope_id   -- (repo scope only) the repo name
#
# Contract:
#   - "Configured" means a runner_dir has a `.runner` file. Dirs without
#     it are silently skipped (matches every existing caller's intent).
#   - The top-level `.bin/` cache dir is skipped.
#   - Missing RUNNER_HOME -> 0 rows, return 0 (caller owns the UX).
#   - Output is streamable; pipe through grep/awk if a subset is needed.

# Extract the numeric agentId from <dir>/.runner. The agentId equals the
# GitHub runner id used by the labels API (PUT .../actions/runners/{id}/
# labels). Uses a sed extractor for the same reason list_runners reads
# agentName with sed: actions/runner writes a UTF-8 BOM + pretty-printed
# JSON, and this stays jq-less so it works in jq-less containers. Prints
# the id, or nothing if .runner is missing / malformed.
runner_agent_id() {
  local dir="$1"
  sed -n 's/.*"agentId"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
    "${dir}/.runner" 2>/dev/null | head -1
}

list_runners() {
  shopt -s nullglob
  local org_dir org scope_dir scope_id scope name
  for org_dir in "${RUNNER_HOME}"/*/; do
    org=$(basename "${org_dir}")
    [[ ${org} == ".bin" ]] && continue
    for scope_dir in "${org_dir}"*/; do
      [[ -f "$(runner_marker_file "${scope_dir}")" ]] || continue
      scope=$(runner_scope_of "${scope_dir}")
      scope_id=$(basename "${scope_dir}")
      [[ ${scope} == "org" ]] && scope_id=""
      # actions/runner writes a UTF-8 BOM + pretty-printed JSON to
      # .runner. agentName lives on its own line; a bash-only regex
      # extractor avoids depending on jq (which keeps list_runners
      # testable in jq-less containers). Falls back to "?" so an empty
      # / corrupt .runner does not break consumers that IFS-split rows.
      name=$(sed -n 's/.*"agentName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
             "$(runner_marker_file "${scope_dir}")" | head -1)
      [[ -z ${name} ]] && name="?"
      if [[ -z ${scope_id} ]]; then
        printf '%s\t%s\t%s\t%s\n' \
          "${scope}" "${org}" "${name}" "${scope_dir%/}"
      else
        printf '%s\t%s\t%s\t%s\t%s\n' \
          "${scope}" "${org}" "${name}" "${scope_dir%/}" "${scope_id}"
      fi
    done
  done
}

# Flip the Default runner group's allows_public_repositories flag on, so
# workflows in public repos within the org can actually dispatch to the
# newly-registered self-hosted runner. GitHub's 2024+ default is false,
# which silently strands public-repo jobs in queued state (the runner is
# online and idle, but never receives JobRequest). We rely on the
# org-level "Require approval for all outside collaborators" gate (set per
# ADR-0011 Public repo security) for the security boundary the GitHub
# default would otherwise enforce.
#
# Idempotent: PATCH succeeds whether the flag is already true or not.
# Safe to call after every add-runner.sh invocation.
enable_public_repos_dispatch() {
  local org=$1
  _gh api -X PATCH \
    "/orgs/${org}/actions/runner-groups/1" \
    -F allows_public_repositories=true \
    --jq '.allows_public_repositories' >/dev/null
}

# Read whether an org's Default runner group allows public-repo workflow
# dispatch -- the GET counterpart to enable_public_repos_dispatch. Echoes
# "true" / "false", or empty on any API error (status.sh maps those to
# public-ok / public-BLOCKED / n/a). Both spell the runner-group-1 endpoint
# here so the _gh seam stays the single GitHub mock point.
github_public_dispatch_status() {
  _gh api "/orgs/$1/actions/runner-groups/1" \
    --jq '.allows_public_repositories' 2>/dev/null || echo ""
}

# Read the org's fork-PR contributor approval policy -- the gate that decides
# whether an outside contributor's fork-PR workflow runs without manual
# approval. "all_external_contributors" is the safe value (every outside
# contributor's run needs approval). Any other policy (first_time_contributors,
# none, ...) leaves the fork-PR hole open, which matters once public-repo
# dispatch is enabled (enable_public_repos_dispatch). Echoes the policy string,
# or empty on any API error. Single _gh seam. #48.
github_fork_pr_approval_policy() {
  _gh api "/orgs/$1/actions/permissions/fork-pr-contributor-approval" \
    --jq '.approval_policy' 2>/dev/null || echo ""
}

# True when the org's fork-PR approval gate is set to the safe policy, i.e.
# every outside contributor's fork-PR workflow requires approval. This is the
# complementary protection enable_public_repos_dispatch relies on. #48.
fork_pr_gate_is_safe() {
  [[ "$(github_fork_pr_approval_policy "$1")" == "all_external_contributors" ]]
}

# (runner_service_running moved to lib/runner-service.sh, alongside the
# svc.sh lifecycle seam it belongs with.)

# --- Destructive-action policy (C2) -------------------------------------
# The flag/confirm/summary policy shared verbatim by cleanup.sh and
# uninstall.sh. The per-item loop + plan rendering differ between those two
# and stay in each script; only this identical half lives here.

# Parse the destructive-script flag set into the YES / DRY_RUN globals.
# The caller must define a usage() function: this helper invokes it for
# -h / --help (exit 0) and for an unknown option (exit 1), exactly as the
# scripts did inline.
parse_destructive_flags() {
  YES=0
  DRY_RUN=0
  while [[ $# -gt 0 ]]; do
    case $1 in
      -y|--yes)     YES=1; shift ;;
      -n|--dry-run) DRY_RUN=1; shift ;;
      -h|--help)    usage; exit 0 ;;
      *) echo "unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
  done
}

# Gate a destructive action behind confirmation. Returns 0 to proceed.
#   confirm_or_abort <prompt>
# - YES=1 -> proceed silently.
# - Non-TTY stdin without --yes -> refuse (exit 1); --yes is mandatory for
#   unattended runs so nothing destructive happens without an explicit opt-in.
# - Interactive -> prompt; anything but y/Y/yes/YES aborts (exit 0).
confirm_or_abort() {
  (( YES )) && return 0
  if [[ ! -t 0 ]]; then
    echo "FAIL: non-interactive run requires --yes (stdin is not a TTY)" >&2
    exit 1
  fi
  local ans
  read -r -p "$1" ans
  case ${ans} in
    y|Y|yes|YES) return 0 ;;
    *) echo "Aborted."; exit 0 ;;
  esac
}

# Print the run summary and exit with the matching code.
#   print_summary <removed> <failed> [fail_label...]
# 0 failures -> "Summary: N removed, 0 failed." and exit 0; otherwise the
# count plus one indented line per failure, and exit 1.
print_summary() {
  local removed=$1 failed=$2
  shift 2
  echo
  if (( failed == 0 )); then
    echo "Summary: ${removed} removed, 0 failed."
    exit 0
  fi
  echo "Summary: ${removed} removed, ${failed} failed."
  printf '  %s\n' "$@"
  exit 1
}

# Percent (integer, no `%`) of the filesystem that holds <path> currently in
# use, via `df -P` (POSIX layout: the Use% is column 5 of the data row, which
# df may wrap onto a second physical line for long device names -- `-P` keeps
# it on one logical record). Echoes e.g. "87", or nothing if df fails. #55.
disk_usage_percent() {
  df -P "$1" 2>/dev/null | awk 'NR==2 { sub(/%$/, "", $5); print $5 }'
}

# --- GitHub API adapter (C1) --------------------------------------------
# Every verb below reaches GitHub through this single private wrapper, so
# the whole adapter is shadowable in one place: tests redefine _gh() after
# sourcing this file and never touch the network. Production just forwards
# to the real gh CLI.
_gh() { command gh "$@"; }

# U3: hard pre-gate for the mutating scripts (add-runner / remove-runner /
# set-labels). Call it AFTER local arg/state validation but BEFORE the first
# gh mutation, so an unauthenticated host fails with one clear line instead
# of gh's raw error mid-operation (and, for remove-runner, before any service
# teardown that could otherwise strand a half-deregistered runner).
require_gh_auth() {
  _gh auth status >/dev/null 2>&1 || {
    echo "FAIL: gh not authenticated (run: gh auth login --scopes admin:org)" >&2
    exit 1
  }
}

# (Tarball integrity SEC-5 -- verify_sha256 / runner_asset_digest /
# verify_runner_tarball -- moved to lib/runner-release.sh.)

# The runners collection path for a scope -- the single source of truth that
# status.sh / set-labels.sh build their per-runner endpoints from, instead
# of re-deriving "/orgs/<org>/actions/runners" by hand. resolve_target's
# TARGET_API_* paths are this base plus a suffix.
#   runner_api_base org <org>           -> /orgs/<org>/actions/runners
#   runner_api_base repo <owner> <repo> -> /repos/<owner>/<repo>/actions/runners
runner_api_base() {
  case $1 in
    org)  printf '/orgs/%s/actions/runners' "$2" ;;
    repo) printf '/repos/%s/%s/actions/runners' "$2" "$3" ;;
    *)    return 1 ;;
  esac
}

# Online status + custom labels for one registered runner, in ONE call.
#   github_runner_status <runners_base> <name>
# <runners_base> is the runners collection path (see runner_api_base).
# Prints "<status>\t<labels-csv>" for the matching runner.
# Exit: 0 found / 2 call succeeded but no runner by that name / 1 gh failed.
# Callers own the display vocabulary (n/a, not-found, ...); this verb only
# reports what GitHub said.
github_runner_status() {
  local base=$1 name=$2 out
  out=$(_gh api "${base}" \
    --jq "[.runners[] | select(.name==\"${name}\") | .status + \"\t\" + ([.labels[].name] | join(\",\"))][0] // empty") \
    || return 1
  [[ -z ${out} ]] && return 2
  printf '%s\n' "${out}"
}

# POST a registration / remove token endpoint and print the .token value.
#   github_runner_token <token_path>
# Used by add-runner (TARGET_API_TOKEN_PATH) and remove-runner
# (TARGET_API_REMOVE_PATH). Exits non-zero if the gh call fails.
github_runner_token() {
  _gh api -X POST "$1" --jq .token
}

# Generate a JIT config and print its .encoded_jit_config (ADR-0001, #80) --
# the server-side, single-use runner configuration that replaces the
# registration-token + config.sh-once path (no long-lived token on the host,
# no .runner marker). The endpoint is scope-specific
# (.../generate-jitconfig); the caller passes the full path (see
# runner_config_jit_generate), so this verb stays scope-agnostic.
#   github_jit_config_generate <jitconfig_path> <name> <runner_group_id> <labels> <work_folder>
# Builds the repeated -f labels[]=<token> fields the endpoint expects (as
# github_set_labels does), POSTs the name / runner_group_id / work_folder
# JSON body, and extracts the one field a JIT runner consumes. Exits
# non-zero if the gh call fails. Caller validates <labels> (validate_labels).
github_jit_config_generate() {
  local path=$1 name=$2 group_id=$3 csv=$4 work=$5
  local -a fields=()
  local tok
  local IFS=','
  for tok in ${csv}; do
    fields+=(-f "labels[]=${tok}")
  done
  _gh api -X POST "${path}" \
    -f "name=${name}" \
    -F "runner_group_id=${group_id}" \
    -f "work_folder=${work}" \
    "${fields[@]}" \
    --jq .encoded_jit_config
}

# Replace a runner's custom labels via PUT, printing the resulting label
# set as one CSV line.
#   github_set_labels <runners_base> <runner_id> <csv>
# Builds the repeated -f labels[]=<token> fields the endpoint expects.
# Caller is responsible for validating <csv> (see validate_labels).
github_set_labels() {
  local base=$1 id=$2 csv=$3
  local -a fields=()
  local tok
  local IFS=','
  for tok in ${csv}; do
    fields+=(-f "labels[]=${tok}")
  done
  _gh api --method PUT "${base}/${id}/labels" "${fields[@]}" \
    --jq '.labels[].name' | paste -sd ',' -
}

# Populates TARGET_URL, TARGET_DIR, TARGET_NAME, TARGET_API_TOKEN_PATH,
# TARGET_API_REMOVE_PATH from positional args.
# Usage:
#   resolve_target org <org>
#   resolve_target repo <owner> <repo>
resolve_target() {
  local scope=$1; shift
  case ${scope} in
    org)
      [[ $# -eq 1 ]] || { echo "usage: $(basename "$0") org <org>" >&2; exit 1; }
      local org=$1
      valid_owner "${org}" || { echo "invalid org: '${org}'" >&2; exit 1; }
      TARGET_URL="https://github.com/${org}"
      TARGET_DIR="$(runner_dir org "${org}")"
      TARGET_NAME="$(runner_agent_name org "${org}")"
      TARGET_API_TOKEN_PATH="/orgs/${org}/actions/runners/registration-token"
      TARGET_API_REMOVE_PATH="/orgs/${org}/actions/runners/remove-token"
      ;;
    repo)
      [[ $# -eq 2 ]] || { echo "usage: $(basename "$0") repo <owner> <repo>" >&2; exit 1; }
      local owner=$1 repo=$2
      { valid_owner "${owner}" && valid_repo "${repo}"; } \
        || { echo "invalid owner/repo: '${owner}/${repo}'" >&2; exit 1; }
      TARGET_URL="https://github.com/${owner}/${repo}"
      TARGET_DIR="$(runner_dir repo "${owner}" "${repo}")"
      TARGET_NAME="$(runner_agent_name repo "${owner}" "${repo}")"
      TARGET_API_TOKEN_PATH="/repos/${owner}/${repo}/actions/runners/registration-token"
      TARGET_API_REMOVE_PATH="/repos/${owner}/${repo}/actions/runners/remove-token"
      ;;
    *)
      echo "usage: {org <org> | repo <owner> <repo>}" >&2
      exit 1
      ;;
  esac
}
