# Shared constants and helpers for github_runner scripts.
# This file is sourced by every script under script/ (init, add-runner,
# remove-runner, status, update, uninstall, cleanup, schedule-cleanup)
# -- variables that look unused here are consumed in those scripts.
# shellcheck shell=bash
# shellcheck disable=SC2034

# RUNNER_HOME holds the tarball cache (.bin/) and per-target runner install
# dirs (<org>/_org/, <owner>/<repo>/). It defaults to <repo_root>/runners/
# (i.e. alongside this checkout) so a single clone owns all runner state
# without polluting $HOME. Override with RUNNER_HOME=... before invoking
# any script to install runners elsewhere.
if [[ -z "${RUNNER_HOME:-}" ]]; then
  RUNNER_HOME="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)/runners"
fi
# SEC-3: RUNNER_HOME becomes the rm -rf root for remove-runner / uninstall /
# cleanup, so refuse dangerous overrides lexically here -- the single
# chokepoint. Validated without requiring the dir to exist, so a first
# install (dir not yet created) is not broken. --preserve-root would not
# help: every consumer derives a SUBPATH (/.bin, /<org>/_org).
[[ "${RUNNER_HOME}" = /* ]] || { echo "FATAL: RUNNER_HOME must be absolute: '${RUNNER_HOME}'" >&2; exit 1; }
RUNNER_HOME="${RUNNER_HOME%/}"
case "${RUNNER_HOME}" in
  ""|/|/.|/..|"${HOME:-}") echo "FATAL: refusing RUNNER_HOME='${RUNNER_HOME}'" >&2; exit 1 ;;
esac
case "/${RUNNER_HOME}/" in
  */../*) echo "FATAL: RUNNER_HOME must be normalized (no '..'): '${RUNNER_HOME}'" >&2; exit 1 ;;
esac
readonly RUNNER_HOME

# Path to the optional registration config (KEY=value, shell-sourceable).
# Generated by script/configure.sh; consumed by load_config below. Lives
# under RUNNER_HOME (gitignored runner state), so config ports with the
# runner state, not the repo.
readonly SETUP_CONF="${RUNNER_HOME}/setup.conf"

# Validate a labels CSV: one or more comma-separated tokens, each matching
# GitHub's allowed label charset [A-Za-z0-9_-]+. Rejects empty input,
# whitespace, and leading / trailing / doubled commas. Returns 0 (valid)
# or 1 (invalid); prints nothing.
validate_labels() {
  [[ "${1:-}" =~ ^[A-Za-z0-9_-]+(,[A-Za-z0-9_-]+)*$ ]]
}

# SEC-4: GitHub owner/org and repo name validators. Owner/org is alphanumerics
# with single internal hyphens (GitHub's rule); repo additionally allows '.'
# and '_' but is never '.' or '..'. Both reject slashes and path traversal, so
# values that reach TARGET_DIR (an rm -rf root) and gh API paths stay safe.
valid_owner() { [[ "$1" =~ ^[A-Za-z0-9](-?[A-Za-z0-9])*$ ]]; }
valid_repo()  { [[ "$1" =~ ^[A-Za-z0-9._-]+$ && "$1" != . && "$1" != .. ]]; }

# Resolve registration labels from the optional setup.conf, leaving $LABELS
# holding the result (default "gpu" when unset / no config file). Called by
# init.sh / add-runner.sh before invoking the runner's config.sh, so a fresh
# install with no setup.conf keeps the historical gpu-only behavior.
#
# SEC-6: setup.conf lives under RUNNER_HOME and is writable by the runner
# user, so a CI job could drop arbitrary shell into it. We therefore EXTRACT
# the LABELS value with sed instead of sourcing the file (which would execute
# any other lines), then re-validate it -- failing closed on anything that
# isn't a clean labels CSV. sed '.../p | tail -1' is busybox-portable and
# mirrors configure.sh's "last LABELS= line wins" upsert.
load_config() {
  LABELS=""
  if [[ -f "${SETUP_CONF}" ]]; then
    LABELS=$(sed -n 's/^LABELS=//p' "${SETUP_CONF}" | tail -1)
  fi
  if [[ -n "${LABELS}" ]] && ! validate_labels "${LABELS}"; then
    echo "FAIL: invalid LABELS in ${SETUP_CONF}: '${LABELS}'" >&2
    exit 1
  fi
  LABELS="${LABELS:-gpu}"
}

# Static fallback used when dynamic resolution fails (offline, gh missing /
# unauthenticated, GitHub rate-limited). Bump opportunistically when fresh
# installs in those degraded states should not start months behind. GitHub
# self-hosted runners always self-update on connect, so this is only the
# bootstrap version, not the runtime one. Refs #10.
readonly RUNNER_VERSION_FALLBACK="2.334.0"

# Resolve the actions/runner version to download:
#   1. If $RUNNER_VERSION is set, honour it verbatim (caller knows best).
#   2. Otherwise ask GitHub for the latest released tag.
#   3. If gh is missing / unauthenticated / network-unreachable / the
#      response is empty for any other reason, fall back to
#      $RUNNER_VERSION_FALLBACK.
#
# Output: bare version string (no leading 'v'), e.g. "2.334.0".
resolve_runner_version() {
  if [[ -n "${RUNNER_VERSION:-}" ]]; then
    echo "${RUNNER_VERSION}"
    return
  fi
  if ! command -v gh >/dev/null 2>&1; then
    echo "${RUNNER_VERSION_FALLBACK}"
    return
  fi
  local resolved
  resolved=$(gh api /repos/actions/runner/releases/latest --jq .tag_name 2>/dev/null \
             | sed 's/^v//' || true)
  if [[ -z ${resolved} ]]; then
    echo "${RUNNER_VERSION_FALLBACK}"
    return
  fi
  echo "${resolved}"
}

# Return the path to the highest-version cached tarball under
# ${RUNNER_HOME}/.bin/, or empty if none. Multiple tarballs may coexist
# (e.g. after an update.sh bump that kept the prior one); add-runner.sh
# uses the highest so newly-registered runners do not start behind.
find_cached_tarball() {
  shopt -s nullglob
  local candidates=("${RUNNER_HOME}/.bin/"actions-runner-linux-x64-*.tar.gz)
  shopt -u nullglob
  if (( ${#candidates[@]} == 0 )); then
    return
  fi
  printf '%s\n' "${candidates[@]}" | sort -V | tail -1
}

# Enumerate every configured runner under RUNNER_HOME. Emits one
# TAB-separated row per runner. Org-scoped rows have 4 fields; repo-scoped
# rows append a 5th:
#
#   org-scoped:   scope \t org   \t name \t runner_dir
#   repo-scoped:  scope \t owner \t name \t runner_dir \t repo
#
# The variable-arity shape exists so callers can `IFS=$'\t' read -r scope
# org name runner_dir scope_id`; bash collapses adjacent tabs when IFS is
# whitespace, so a fixed-arity row with an empty middle field would lose
# alignment. Trailing-optional avoids that.
#
# Fields:
#   scope      -- "org" or "repo"
#   org        -- org name (for org scope) or owner name (for repo scope)
#   name       -- agentName read from the .runner JSON marker file
#   runner_dir -- absolute path to the actions/runner state dir
#   scope_id   -- (repo scope only) the repo name
#
# Contract:
#   - "Configured" means a runner_dir has a `.runner` file. Dirs without
#     it are silently skipped (matches every existing caller's intent).
#   - The top-level `.bin/` cache dir is skipped.
#   - Missing RUNNER_HOME -> 0 rows, return 0 (caller owns the UX).
#   - Output is streamable; pipe through grep/awk if a subset is needed.

# Extract the numeric agentId from <dir>/.runner. The agentId equals the
# GitHub runner id used by the labels API (PUT .../actions/runners/{id}/
# labels). Uses a sed extractor for the same reason list_runners reads
# agentName with sed: actions/runner writes a UTF-8 BOM + pretty-printed
# JSON, and this stays jq-less so it works in jq-less containers. Prints
# the id, or nothing if .runner is missing / malformed.
runner_agent_id() {
  local dir="$1"
  sed -n 's/.*"agentId"[[:space:]]*:[[:space:]]*\([0-9][0-9]*\).*/\1/p' \
    "${dir}/.runner" 2>/dev/null | head -1
}

list_runners() {
  shopt -s nullglob
  local org_dir org scope_dir scope_id scope name
  for org_dir in "${RUNNER_HOME}"/*/; do
    org=$(basename "${org_dir}")
    [[ ${org} == ".bin" ]] && continue
    for scope_dir in "${org_dir}"*/; do
      [[ -f "${scope_dir}.runner" ]] || continue
      scope_id=$(basename "${scope_dir}")
      if [[ ${scope_id} == "_org" ]]; then
        scope="org"
        scope_id=""
      else
        scope="repo"
      fi
      # actions/runner writes a UTF-8 BOM + pretty-printed JSON to
      # .runner. agentName lives on its own line; a bash-only regex
      # extractor avoids depending on jq (which keeps list_runners
      # testable in jq-less containers). Falls back to "?" so an empty
      # / corrupt .runner does not break consumers that IFS-split rows.
      name=$(sed -n 's/.*"agentName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
             "${scope_dir}.runner" | head -1)
      [[ -z ${name} ]] && name="?"
      if [[ -z ${scope_id} ]]; then
        printf '%s\t%s\t%s\t%s\n' \
          "${scope}" "${org}" "${name}" "${scope_dir%/}"
      else
        printf '%s\t%s\t%s\t%s\t%s\n' \
          "${scope}" "${org}" "${name}" "${scope_dir%/}" "${scope_id}"
      fi
    done
  done
}

# Flip the Default runner group's allows_public_repositories flag on, so
# workflows in public repos within the org can actually dispatch to the
# newly-registered self-hosted runner. GitHub's 2024+ default is false,
# which silently strands public-repo jobs in queued state (the runner is
# online and idle, but never receives JobRequest). We rely on the
# org-level "Require approval for all outside collaborators" gate (set per
# ADR-0011 Public repo security) for the security boundary the GitHub
# default would otherwise enforce.
#
# Idempotent: PATCH succeeds whether the flag is already true or not.
# Safe to call after every add-runner.sh invocation.
enable_public_repos_dispatch() {
  local org=$1
  gh api -X PATCH \
    "/orgs/${org}/actions/runner-groups/1" \
    -F allows_public_repositories=true \
    --jq '.allows_public_repositories' >/dev/null
}

# Is the systemd service for a registered runner currently loaded/running?
#   runner_service_running <runner-name>
# Owns the actions/runner unit-name convention -- actions.runner.<url-slug>.
# <runner-name>.service -- in one place. The name is anchored between a dot
# and ".service" so a runner whose name is a prefix of another's (myorg vs
# myorg-2) cannot produce a false positive. Returns 0 (running) / 1 (not).
runner_service_running() {
  local name=$1
  systemctl list-units --type=service --no-legend 2>/dev/null \
    | grep -qE "actions\.runner\..*\.${name}\.service"
}

# --- Destructive-action policy (C2) -------------------------------------
# The flag/confirm/summary policy shared verbatim by cleanup.sh and
# uninstall.sh. The per-item loop + plan rendering differ between those two
# and stay in each script; only this identical half lives here.

# Parse the destructive-script flag set into the YES / DRY_RUN globals.
# The caller must define a usage() function: this helper invokes it for
# -h / --help (exit 0) and for an unknown option (exit 1), exactly as the
# scripts did inline.
parse_destructive_flags() {
  YES=0
  DRY_RUN=0
  while [[ $# -gt 0 ]]; do
    case $1 in
      -y|--yes)     YES=1; shift ;;
      -n|--dry-run) DRY_RUN=1; shift ;;
      -h|--help)    usage; exit 0 ;;
      *) echo "unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
  done
}

# Gate a destructive action behind confirmation. Returns 0 to proceed.
#   confirm_or_abort <prompt>
# - YES=1 -> proceed silently.
# - Non-TTY stdin without --yes -> refuse (exit 1); --yes is mandatory for
#   unattended runs so nothing destructive happens without an explicit opt-in.
# - Interactive -> prompt; anything but y/Y/yes/YES aborts (exit 0).
confirm_or_abort() {
  (( YES )) && return 0
  if [[ ! -t 0 ]]; then
    echo "FAIL: non-interactive run requires --yes (stdin is not a TTY)" >&2
    exit 1
  fi
  local ans
  read -r -p "$1" ans
  case ${ans} in
    y|Y|yes|YES) return 0 ;;
    *) echo "Aborted."; exit 0 ;;
  esac
}

# Print the run summary and exit with the matching code.
#   print_summary <removed> <failed> [fail_label...]
# 0 failures -> "Summary: N removed, 0 failed." and exit 0; otherwise the
# count plus one indented line per failure, and exit 1.
print_summary() {
  local removed=$1 failed=$2
  shift 2
  echo
  if (( failed == 0 )); then
    echo "Summary: ${removed} removed, 0 failed."
    exit 0
  fi
  echo "Summary: ${removed} removed, ${failed} failed."
  printf '  %s\n' "$@"
  exit 1
}

# --- GitHub API adapter (C1) --------------------------------------------
# Every verb below reaches GitHub through this single private wrapper, so
# the whole adapter is shadowable in one place: tests redefine _gh() after
# sourcing this file and never touch the network. Production just forwards
# to the real gh CLI.
_gh() { command gh "$@"; }

# The runners collection path for a scope -- the single source of truth that
# status.sh / set-labels.sh build their per-runner endpoints from, instead
# of re-deriving "/orgs/<org>/actions/runners" by hand. resolve_target's
# TARGET_API_* paths are this base plus a suffix.
#   runner_api_base org <org>           -> /orgs/<org>/actions/runners
#   runner_api_base repo <owner> <repo> -> /repos/<owner>/<repo>/actions/runners
runner_api_base() {
  case $1 in
    org)  printf '/orgs/%s/actions/runners' "$2" ;;
    repo) printf '/repos/%s/%s/actions/runners' "$2" "$3" ;;
    *)    return 1 ;;
  esac
}

# Online status + custom labels for one registered runner, in ONE call.
#   github_runner_status <runners_base> <name>
# <runners_base> is the runners collection path (see runner_api_base).
# Prints "<status>\t<labels-csv>" for the matching runner.
# Exit: 0 found / 2 call succeeded but no runner by that name / 1 gh failed.
# Callers own the display vocabulary (n/a, not-found, ...); this verb only
# reports what GitHub said.
github_runner_status() {
  local base=$1 name=$2 out
  out=$(_gh api "${base}" \
    --jq "[.runners[] | select(.name==\"${name}\") | .status + \"\t\" + ([.labels[].name] | join(\",\"))][0] // empty") \
    || return 1
  [[ -z ${out} ]] && return 2
  printf '%s\n' "${out}"
}

# POST a registration / remove token endpoint and print the .token value.
#   github_runner_token <token_path>
# Used by add-runner (TARGET_API_TOKEN_PATH) and remove-runner
# (TARGET_API_REMOVE_PATH). Exits non-zero if the gh call fails.
github_runner_token() {
  _gh api -X POST "$1" --jq .token
}

# Replace a runner's custom labels via PUT, printing the resulting label
# set as one CSV line.
#   github_set_labels <runners_base> <runner_id> <csv>
# Builds the repeated -f labels[]=<token> fields the endpoint expects.
# Caller is responsible for validating <csv> (see validate_labels).
github_set_labels() {
  local base=$1 id=$2 csv=$3
  local -a fields=()
  local tok
  local IFS=','
  for tok in ${csv}; do
    fields+=(-f "labels[]=${tok}")
  done
  _gh api --method PUT "${base}/${id}/labels" "${fields[@]}" \
    --jq '.labels[].name' | paste -sd ',' -
}

# Populates TARGET_URL, TARGET_DIR, TARGET_NAME, TARGET_API_TOKEN_PATH,
# TARGET_API_REMOVE_PATH from positional args.
# Usage:
#   resolve_target org <org>
#   resolve_target repo <owner> <repo>
resolve_target() {
  local scope=$1; shift
  case ${scope} in
    org)
      [[ $# -eq 1 ]] || { echo "usage: ... org <org>" >&2; exit 1; }
      local org=$1
      valid_owner "${org}" || { echo "invalid org: '${org}'" >&2; exit 1; }
      TARGET_URL="https://github.com/${org}"
      TARGET_DIR="${RUNNER_HOME}/${org}/_org"
      TARGET_NAME="$(hostname)-${org}-org"
      TARGET_API_TOKEN_PATH="/orgs/${org}/actions/runners/registration-token"
      TARGET_API_REMOVE_PATH="/orgs/${org}/actions/runners/remove-token"
      ;;
    repo)
      [[ $# -eq 2 ]] || { echo "usage: ... repo <owner> <repo>" >&2; exit 1; }
      local owner=$1 repo=$2
      { valid_owner "${owner}" && valid_repo "${repo}"; } \
        || { echo "invalid owner/repo: '${owner}/${repo}'" >&2; exit 1; }
      TARGET_URL="https://github.com/${owner}/${repo}"
      TARGET_DIR="${RUNNER_HOME}/${owner}/${repo}"
      TARGET_NAME="$(hostname)-${owner}-${repo}"
      TARGET_API_TOKEN_PATH="/repos/${owner}/${repo}/actions/runners/registration-token"
      TARGET_API_REMOVE_PATH="/repos/${owner}/${repo}/actions/runners/remove-token"
      ;;
    *)
      echo "usage: {org <org> | repo <owner> <repo>}" >&2
      exit 1
      ;;
  esac
}
